apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tssc-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/lucarval/private-image:jenkins-f2ecc95de4a6a040a21616739913cd7cac2815ec
          name: container-image
